dist: xenial
language: minimal

services:
- docker

before_install:
- curl -LO https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl && chmod +x kubectl
- mkdir -p ~/.kube && echo $KUBECONFIG_BASE64 | base64 -d > ~/.kube/config

script:
- export DOCKER_HUB_IMAGE=aybaze/aybot
- export TAG=$TRAVIS_BUILD_NUMBER
- docker build -t $DOCKER_HUB_IMAGE .
- docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
- docker tag $DOCKER_HUB_IMAGE $DOCKER_HUB_IMAGE:$TAG
- docker push $DOCKER_HUB_IMAGE:$TAG
- docker push $DOCKER_HUB_IMAGE
- ./kubectl apply -f kubernetes/aybot.yaml
- ./kubectl set image deployment aybot aybot=aybaze/aybot:$TAG
