version: 2
jobs:
  build:
    docker:
      - image: docker
    working_directory: /aybot
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build Docker image
          command: |
            docker build --cache-from=aybot -t aybot .
      - deploy:
          name: Push Docker image
          command: |
            TAG=$CIRCLE_BUILD_NUM
            DOCKER_HUB_IMAGE=aybaze/aybot
            docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
            docker tag aybot $DOCKER_HUB_IMAGE
            docker tag aybot $DOCKER_HUB_IMAGE:$TAG
            docker push $DOCKER_HUB_IMAGE:$TAG
            docker push $DOCKER_HUB_IMAGE
            mkdir -p /tmp/workspace && cd /tmp/workspace && echo ${TAG} > tag.txt
      - persist_to_workspace:
          root: /tmp/workspace
          paths:
            - tag.txt
  deploy_kubernetes:
    docker:
      - image: circleci/python
    steps:
      - checkout
      - attach_workspace: &attach_workspace
          at: /tmp/workspace
      - run:
          name: Download kubectl
          command: curl -LO https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl && chmod +x kubectl
      - run:
          name: Retrieve kubeconfig from ENV
          command: mkdir -p ~/.kube && echo $KUBECONFIG_BASE64 | base64 -d > ~/.kube/config
      - run:
          name: Install aybot
          command: ./kubectl apply -f kubernetes/aybot.yaml
      - run:
          name: Set image to current build
          command: |
            export TAG="$(cat /tmp/workspace/tag.txt)"
            ./kubectl set image deployment aybot aybot=aybaze/aybot:$TAG
workflows:
  version: 2
  build-test-and-deploy:
    jobs:
      - build:
          context: org-global
      - deploy_kubernetes:
          context: org-global
          requires:
            - build
